"""
test_loads_003.py -- validation gate for Phase 3 module 1 (loads.py)

Candidate geometry = 003 rebuilt from design inputs only (tip D, taper,
tube lengths, thicknesses). Loads are then generated by loads.py and
compared against what PLS-POLE reported.

Check A  per-segment shaft loads vs 'detailed_pole_loading_data'
Check B  load totals vs base reactions, all 21 load cases
Check C  section moment / axial / shear at every PLS check point, using
         PLS's OWN deflected shape to supply the P-delta. This isolates the
         load model (magnitudes + lever arms) from the deflection solver,
         which is module 2.
Check D  first-order (no P-delta) base moment vs PLS -> size of P-delta.
"""
import math
import numpy as np
from geometry import PoleSpec, Segment
from loads import Baseline, build_load_model, first_order_forces
from pls_pole_xml_parser import (parse_pls_pole_xml, get_field as g,
                                 get_single_table, get_load_case_instances)

XML = '/mnt/user-data/uploads/003_T316-S-02_110FT_FDN.xml'
SPEC = PoleSpec(label='003', tip_diameter=13.00, taper=0.32955, embedment=0.0,
                segments=[Segment(57.0, 0.3125, joint_type='slip'),
                          Segment(57.5, 0.375, joint_type='flange')])

base = Baseline.from_xml(XML)
p = parse_pls_pole_xml(XML)
H = SPEC.total_length


def pct(a, b):
    return (a / b - 1) * 100 if abs(b) > 1e-9 else float('nan')


# ---------------------------------------------------------------- A
print('=' * 78)
print('A. Per-segment shaft loads vs PLS detailed_pole_loading_data')
worst = dict(D=0, wind=0, wt=0, ice=0)
for case, rows in get_load_case_instances(p, 'detailed_pole_loading_data').items():
    m = build_load_model(SPEC, base, case, ds=0.05)
    if m.case.q_trans < 1.0:
        continue    # PEC ice case: q=0 in the case table; PLS shows ~0.1 psf residue (lbs-level)
    for r in rows:
        zt, zb = g(r, 'section_top_z'), g(r, 'section_bottom_z')
        st, sb = H - zt, H - zb
        sel = [e for e in m.elements if st - 1e-6 <= e.s_mid <= sb + 1e-6]
        wind = sum(e.fy for e in sel) * 1000
        wt = sum(e.area for e in sel) / len(sel) * (sb - st) / 144 * 490 * m.case.dlf
        D = sum(e.D_wind for e in sel) / len(sel)
        pw = g(r, 'pole_wind_load') + g(r, 'pole_ice_wind_load')
        worst['D'] = max(worst['D'], abs(pct(D, g(r, 'outer_diameter'))))
        worst['wind'] = max(worst['wind'], abs(pct(wind, pw)))
        worst['wt'] = max(worst['wt'], abs(pct(wt, g(r, 'pole_vert_load'))))
        ice = sum(e.fz for e in sel) * 1000 - wt
        if g(r, 'pole_ice_vertical_load') > 1:
            worst['ice'] = max(worst['ice'], abs(pct(ice, g(r, 'pole_ice_vertical_load'))))
print(f"  worst |diff| over wind+ice cases x 27 segments:  D {worst['D']:.2f}%   "
      f"wind {worst['wind']:.2f}%   self-wt {worst['wt']:.2f}%   ice wt {worst['ice']:.2f}%")

# ---------------------------------------------------------------- B, C, D
eq = get_load_case_instances(p, 'detailed_steel_pole_usages')
rx = get_load_case_instances(p, 'joint_support_reactions')

print('=' * 78)
print('B/C/D. Totals, section forces with PLS deflected shape, first-order moment')
print(f"{'load case':44s} {'Vy':>6s} {'PLS':>6s} | {'Mbase':>7s} {'PLS':>7s} {'d%':>6s} |"
      f" {'max|dM| all pts':>15s} | {'1st-ord':>7s} {'P-D %':>6s}")
all_M = []
for case in rx:
    m = build_load_model(SPEC, base, case, ds=0.25)
    rows = sorted(eq[case], key=lambda r: g(r, 'rel_dist'))
    s_pts = np.array([g(r, 'rel_dist') for r in rows])
    y_pts = np.array([g(r, 'trans_defl') for r in rows]) / 12.0
    x_pts = np.array([g(r, 'long_defl') for r in rows]) / 12.0
    v_pts = np.array([g(r, 'vert_defl') for r in rows]) / 12.0

    def pos(s):          # deflected centreline position (x, y, z) and tilt
        y = np.interp(s, s_pts, y_pts); x = np.interp(s, s_pts, x_pts)
        z = m.z_of(s) + np.interp(s, s_pts, v_pts)
        e = 0.25
        th = math.atan2(np.interp(max(s - e, 0), s_pts, y_pts) -
                        np.interp(min(s + e, H), s_pts, y_pts), 2 * e)
        return x, y, z, th

    loads = []           # (x, y, z, Fx, Fy, Fz)
    for e in m.elements:
        x, y, z, _ = pos(e.s_mid)
        loads.append((x, y, z, e.fx, e.fy, e.fz, e.s_mid))
    for pl in m.points:
        x, y, z, th = pos(pl.s)
        yy = y + pl.dy * math.cos(th) + pl.dz * math.sin(th)
        zz = z - pl.dy * math.sin(th) + pl.dz * math.cos(th)
        loads.append((x + pl.dx, yy, zz, pl.Fx, pl.Fy, pl.Fz, pl.s))

    maxd = 0.0
    for r in rows:
        s0 = g(r, 'rel_dist')
        if g(r, 'joint_position') == 'Origin' and s0 > 0:
            continue                      # use 'End' rows (just above joint)
        x0, y0, z0, _ = pos(s0)
        above = [L for L in loads if L[6] < s0 - 1e-6]
        Mx = sum(Fy * (z - z0) + Fz * (y - y0) for x, y, z, Fx, Fy, Fz, _ in above)
        Mpls = g(r, 'trans_mom_local_mx')
        if abs(Mpls) > 50:
            maxd = max(maxd, abs(pct(Mx, Mpls)))
            all_M.append(pct(Mx, Mpls))

    x0, y0, z0, _ = pos(H)
    Mb = sum(Fy * (z - z0) + Fz * (y - y0) for x, y, z, Fx, Fy, Fz, _ in loads)
    Vy = sum(L[4] for L in loads)
    R = rx[case][0]
    fo = first_order_forces(m, H - 1e-9)['Mx']
    Mpls = g(R, 'x_moment')
    print(f"{case[:44]:44s} {Vy:6.2f} {-g(R, 'y_force'):6.2f} | {Mb:7.1f} {Mpls:7.1f} "
          f"{pct(Mb, Mpls):+6.2f} | {maxd:14.2f}% | {fo:7.1f} {pct(Mpls, fo):+6.1f}")

a = np.array(all_M)
print(f"\nSection moments, all check points with |M| > 50 ft-k ({len(a)} points): "
      f"mean {a.mean():+.3f}%, max |diff| {np.abs(a).max():.2f}%")
